name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"
          cache: true

      # 1. This generates the local 'notely' binary file
      - name: Build Production
        run: bash scripts/buildprod.sh

      # 2. Authenticate with Google
      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # 3. The '.' now successfully includes the 'notely' binary created in step 1
      - name: Publish container
        run: |
          gcloud builds submit --tag us-central1-docker.pkg.dev/notely-502600/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-502600/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-502600 --max-instances=4
